config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'users/registrations'}
  root 'pages#home'
  resources 'user', only: [:show] do
    resources 'images', except: [:index]
  end
  resources 'tags', only: [:new, :create, :destroy]
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_many :tags
  has_attached_file :photo, :styles => {:small => "100x100#", :large => "650x650>"}
  validates_attachment_presence :photo
  validates :name, presence: true
  validates :caption, presence: true
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @image = Image.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      flash[:notice] = "SHAZAM"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "YOU DONE MESSED UP. OR MAYBE WE DID. YOU GO BACK NOW"
      redirect_to :back
    end
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:alert] = "ALAKAZAM"
    else
      render :edit
    end
  end

  def show
    @image = Image.find(params[:id])
    @user = User.find(params[:user_id])
    @users = User.all
    @tag = Tag.new
    # @tagged_users = []
    # tags.each do |tag|
    #   if tag.image_id == @image.id
    #     @tagged_users.push(tag.user_id)
    #   end
    # end
    #
    # @tagged_users.each_with_index do |user_id, index|
    #   @users.each do |user|
    #     if user_id == user.id
    #       @tagged_users[index] = user.email
    #     end
    #   end
    # end

    @select_options = []
    @users.each do |user|
      @select_options.push([user.email, user.id])
    end

  end

  def edit
    @image = Image.find(params[:id])
  end

  def destroy
    @image = Image.find(params[:id])
    @user = User.find(params[:user_id])
    @image.destroy
    redirect_to user_path(current_user)
  end

  private
  def image_params
    binding.pry
    params.require(:image).permit(:name, :caption, :photo, :user_id)
  end

end

app/views/images/show.html.erb
<div class="centered-full-image">
  <%= image_tag @image.photo(:large) %>
  <br>
  <%= @image.caption %>
</div>

 <%= link_to "Delete Photo", user_image_path(@user, @image), class: "btn btn-danger",
                                        data: {confirm: "Are you sure?",
                                                method: 'delete'} %>
<h3>Tag Someone:</h3>

<%= form_for @tag do |f| %>
  <%= f.hidden_field :image_id, value: @image.id %>
  <%= select_tag "user_id", options_for_select(@select_options), class: 'form-control' %>
  <%= f.submit 'Tag', class: "btn btn-xs btn-success" %>
<% end %>

<h3>Tags on this image:</h3>

<ul>

<% @image.tags.each do |tag| %>
  <li><%= link_to tag.user.email, user_path(tag.user) %></li>
<% end %>
</ul>